#!/bin/sh

if ! command -v curl > /dev/null; then
  echo "Error: Curl is needed to run this script!"
  exit 1
fi

/bin/bash -c "$(curl -fsSL https://gist.github.com/Im-Fran/a81e3270f46994dc0419ed0171cf4305/raw/b97141b3c1e34c0944b06b5780ed4fe487f93844/install_flutter.sh)"
